FROM python

RUN mkdir /service

COPY api_service/requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /service/api_service

COPY api_service/ /service/api_service

ENV GOOGLE_APPLICATION_CREDENTIALS="gemini_key.json"
ENV GOOGLE_MAPS_API_KEY="maps_key.json"


ENV PORT=5000
EXPOSE 5000
ENV FLASK_APP=app.py
ENTRYPOINT [ "flask", "run", "--host=0.0.0.0" , "--debug"]